spring:
  application:
    name: gateway-service

server: 
  port: 8888
  
zuul:
  routes:
    accounts:
      path: /accounts/**
      service-id: account-service
      strip-prefix: false
    customers:
      path: /customers/**
      service-id: customer-service
      strip-prefix: false

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#  you probably wouldn't set it this short in production but will be convenient for dev
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
   
