server:
  port: 8089

spring:
  application:
    name: customer-service

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8762/eureka
#  you probably wouldn't set it this short in production but will be convenient for dev
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

