server:
  port: 8088

spring:
  application:
    name: account-service

eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
#  you probably wouldn't set it this short in production but will be convenient for dev
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

